# -*- coding: utf-8 -*-
"""REGLOG_version 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTDwE_648d1PShuMEU-R2tB2vh6Svkab
"""

# Import des librairies

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

file_path = '/content/open-meteo-33.56N7.62W20m (2).xlsx'
df = pd.read_excel(file_path, index_col=[0], parse_dates =True,header = 0)

df.shape

df.head(10)

df.tail()

df.columns

df.info()

df.nunique().sort_values()

df.describe()

sns.pairplot(df)
plt.show()

plt.figure(figsize=(30,7))
df.boxplot()

sns.histplot(df['temperature_2m (°C)'])

sns.kdeplot(df['temperature_2m (°C)'], shade=True)

plt.figure(figsize=(14,7))
sns.lineplot(x="time", y="temperature_2m (°C)", data=df)

df.corr()

X = df[[col for col in df.columns if col != "temperature_2m (°C)"]]

y = df["temperature_2m (°C)"]

X.shape, y.shape

from sklearn.model_selection import train_test_split

X = df[[col for col in df.columns if col != "temperature_2m (°C)"]]
y = df['temperature_2m (°C)']

X.head()

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.3)

import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression

modele_logit = LogisticRegression()
modele_reglog = linear_model.LogisticRegression(random_state = 0,solver = 'liblinear', multi_class = 'auto')
modele_logit.fit(X_train,y_train)